#SPDX-License-Identifier: MIT-0
---
# tasks file for docker

- block:    # BLOCK FOR DEBIAN
  - name: install required packages
    ansible.builtin.apt:
      pkg:
        - ca-certificates
        - curl
      state: latest
      update_cache: true

  - name: add docker gpg apt key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      state: present

  - name: add docker repository
    ansible.builtin.apt_repository:
      repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present

  - name: install docker-ce
    ansible.builtin.apt:
      name: docker-ce
      state: latest
      update_cache: true

  when: ansible_pkg_mgr == "apt"

- block:    # BLOCK FOR REDHAT
  - name: install required packages
    ansible.builtin.dnf:
      name: dnf-plugins-core
      state: latest
      update_cache: true

  - name: add docker repository
    command: dnf config-manager --add-repo https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo

  - name: install docker-ce
    ansible.builtin.dnf:
      name: docker-ce
      state: latest
      update_cache: true

  when: ansible_pkg_mgr == "dnf"

- name: start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: create a container
  community.docker.docker_container:
    name: red
    state: started
    image: 4sinl/ansible-task
    ports:
      - "80:80"
    env:
      PORT: "80"